import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/lib/Components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hospital Managemt System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-10`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
